### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by tipa** [btripp/FlexboxLayoutXamarinBindingAndroid#1]
Any chance to get updates for this Binding library? Current version is 0.2.6 and there is a 0.3.0 alpha version with the FlexboxLayoutManager that I'd love to use in my Xamarin project, too. Thanks!

**Comment by btripp** [comment]
Hey, I will try to update it when I get a chance. I will respond to this issue when I do so.

**Comment by btripp** [comment]
Hey @tipa, I just updated the binding library to Googles latest version. It may take a while for Nuget to update properly. Closing the issue.

Thanks!

**Comment by tipa** [comment]
Thanks for the update @btripp! Unfortunately, the class `FlexboxLayoutManager` still seems to be missing, it's in the alpha channel only. I inspected the Manifest in the jar you provide with this Nuget package and it still seems to be the 0.2.6 version.

**Comment by btripp** [comment]
Doh! I can fix that by the end of the day

**Comment by btripp** [comment]
@tipa I just uploaded the alpha version. Please be on the lookout for it.
